version: '3.8'
services:
  db:
    image: postgres:15
    container_name: lajambre-db
    restart: always
    environment:
      POSTGRES_USER: user_lajambre
      POSTGRES_PASSWORD: password_lajambre
      POSTGRES_DB: lajambre_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: