# Etapa 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

# Instalar dependencias
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

# Copiar el resto del código y el schema de Prisma
COPY . .

# Generar cliente de Prisma y compilar NestJS
RUN npx prisma generate
RUN pnpm build

# Etapa 2: Producción (Imagen súper ligera)
FROM node:20-alpine AS production

WORKDIR /app

# Instalar pnpm
RUN npm install -g pnpm

# Copiar package.json y dependencias de producción
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod

# Copiar el cliente de Prisma generado
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/prisma ./prisma

# Copiar el código compilado
COPY --from=builder /app/dist ./dist

# Crear carpeta de subidas de imágenes
RUN mkdir -p /app/uploads && chown -R node:node /app/uploads

# Optimización para Node.js (Liberar memoria más rápido en VPS pequeños)
ENV NODE_ENV=production
ENV NODE_OPTIONS="--max-old-space-size=400"

USER node

EXPOSE 3000

CMD ["node", "dist/main"]
